<a href="https://colab.research.google.com/github/Bxvam/PrimerDepartamental/blob/main/2dep3act.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import cv2
import numpy as np
from google.colab import files
import math

print("Paso 1: Por favor sube tu imagen a continuación:")
uploaded = files.upload()

nombre_archivo = list(uploaded.keys())[0]

def analizar_imagen_con_entropia(ruta_imagen):
    # Cargamos la imagen
    imagen = cv2.imread(ruta_imagen, cv2.IMREAD_UNCHANGED)

    if imagen is None:
        print("Error al leer la imagen.")
        return

    dimensiones = imagen.shape
    print(f"\n--- REPORTE DE LA IMAGEN: {ruta_imagen} ---")

    # --- 1. Información Básica ---
    if len(dimensiones) == 2:
        print(" TIPO: Escala de Grises (1 canal)")
    elif len(dimensiones) == 3:
        canales = dimensiones[2]
        if canales == 3:
            print(" TIPO: Color RGB/BGR (3 canales)")
        elif canales == 4:
            print(" TIPO: Color con Transparencia (4 canales)")

    print(f"📏 TAMAÑO: {dimensiones[0]} alto x {dimensiones[1]} ancho")

    # --- 2. CÁLCULO DE ENTROPÍA ---
    # Paso A: "Aplanamos" la imagen. Convertimos la matriz 2D/3D en una fila gigante de números
    # Esto es necesario para contar la frecuencia de todos los píxeles juntos.
    pixels_planos = imagen.flatten()

    # Paso B: Calculamos el histograma (frecuencia de cada valor de píxel)
    # values = los valores (0-255), counts = cuántas veces aparece cada uno
    values, counts = np.unique(pixels_planos, return_counts=True)

    # Paso C: Normalizamos para obtener probabilidades (p)
    # p = conteo / total_de_pixeles
    probabilidades = counts / len(pixels_planos)

    # Paso D: Fórmula de Shannon: - sum(p * log2(p))
    # Usamos np.log2 para hacerlo rápido con vectores
    entropia = -np.sum(probabilidades * np.log2(probabilidades))

    print(f" ENTROPÍA DE SHANNON: {entropia:.4f} bits")
    print("-" * 40)

    # --- 3. Mostrar Matriz ---
    print(">> MATRIZ NUMÉRICA (Resumen):")
    print(imagen)

# Ejecutamos la función
analizar_imagen_con_entropia(nombre_archivo)

Paso 1: Por favor sube tu imagen a continuación:


Saving 2daAct.jpg to 2daAct (1).jpg

--- REPORTE DE LA IMAGEN: 2daAct (1).jpg ---
 TIPO: Color RGB/BGR (3 canales)
📏 TAMAÑO: 259 alto x 194 ancho
 ENTROPÍA DE SHANNON: 7.9055 bits
----------------------------------------
>> MATRIZ NUMÉRICA (Resumen):
[[[ 15  12   4]
  [ 15  12   4]
  [ 14  11   3]
  ...
  [ 59  58  32]
  [ 61  60  34]
  [ 61  60  34]]

 [[ 15  12   4]
  [ 15  12   4]
  [ 14  11   3]
  ...
  [ 60  59  31]
  [ 62  61  33]
  [ 62  61  33]]

 [[ 15  12   4]
  [ 15  12   4]
  [ 14  11   3]
  ...
  [ 61  60  32]
  [ 63  62  34]
  [ 63  62  34]]

 ...

 [[102 236 140]
  [102 236 140]
  [102 236 140]
  ...
  [151 255 255]
  [149 255 249]
  [149 255 249]]

 [[102 236 140]
  [102 236 140]
  [102 236 140]
  ...
  [140 252 245]
  [149 255 249]
  [149 255 249]]

 [[102 236 140]
  [102 236 140]
  [102 236 140]
  ...
  [134 250 243]
  [149 255 249]
  [149 255 249]]]
